### ISSUE TITLE
simple_baxter_gripper_interface/simple_baxter_gripper_interface.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by Lantidote** [Limuyuantao/baxter_ws#1]
编译时出现
simple_baxter_gripper_interface/simple_baxter_gripper_interface.h: 没有那个文件或目录
请问是否可以上传一下这个包呢

**Comment by Limuyuantao** [comment]
我看看，正在上传

**Comment by Lantidote** [comment]
不好意思我这边看好像README有更新但是文件还是没有传上来

**Comment by Limuyuantao** [comment]
您好！我这上传速度比较慢，有好多没有上传上去，正在更新！你要是特别着急的话，留以下您的邮箱或者微信我给你发过去

**Comment by Lantidote** [comment]
3287477449@qq.com 麻烦您了 baxter包的话我已经下好了 在bilibili看了您的视频特此过来寻求代码学习 感谢

**Comment by Limuyuantao** [comment]
已经发送您邮件了，请查收！

**Comment by Limuyuantao** [comment]
github 这个上面的代码也更新好了，有问题及时沟通交流！

**Comment by Lantidote** [comment]
嗯嗯好的 再次感谢
